name: Flutter CI

on: push
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout_repo
      uses: actions/checkout@v1 
    - name: setup_java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: setup_flutter
      working-directory: ./default_app
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' 
    - run: flutter pub get
    - run: flutter build aot
    # Analyze our Dart code
    - run: flutter analyze
    # Run our tests
    - run: flutter test
