name: Flutter CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      working-directory: Flutter-CI-Demo/default_app
      run: pub get
    - name: Run tests
      working-directory: Flutter-CI-Demo/default_app
      run: pub run test
